GET http://localhost:8080/posts HTTP/1.1
content-type: application/json

###

POST http://localhost:8080/posts HTTP/1.1
content-type: application/json

{
    "title": "Title",
    "body": "Body of the post with exactly eight words"
}