apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  selector:
    matchLabels:
      app: posts-depl
  template:
    metadata:
      labels:
        app: posts-depl
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "posts-depl"
        dapr.io/app-port: "80"
        dapr.io/config: "tracing"
        dapr.io/log-level: "debug"
    spec:
      containers:
      - name: posts-depl
        image: posts-service
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "125m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  type: ClusterIP
  selector:
    app: posts-depl
  ports:
  - port: 80
    targetPort: 80

